name: aws_image
description: "A Flutter package for loading, caching, and displaying images from AWS S3 using presigned URLs or BuckerKey"
version: 2.0.2
homepage: https://github.com/kishormainali/aws_image
repository: https://github.com/kishormainali/aws_image

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.1

  crypto: ^3.0.7
  path: any
  path_provider: ^2.1.5
  mime: ^2.0.0
  fp_logger: ^3.1.1
  meta: any # For annotations like @required
  flutter_svg: ^2.2.3
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
